
import java.awt.Color;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.util.concurrent.atomic.AtomicInteger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import org.mindrot.jbcrypt.BCrypt;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author seany
 */



public class LoginSystem extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginSystem.class.getName());
    
    private volatile boolean isSigningUp = false;
    private volatile boolean isSigningIn = false;
    
    private String currentUsername;
    
    /**
     * Creates new form BasicSignInSystem
     */
    public LoginSystem() {
        initComponents();
        initFieldListeners();
        isSignIn(true);
        AdminPanel.setVisible(false);
        UserPanel.setVisible(false);
        hideLoadingPanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    private void isSignIn(boolean ifSignIn){
        if(ifSignIn){
            SignInPanel.setVisible(true);
            SignUpPanel.setVisible(false);
        }else{
            SignUpPanel.setVisible(true);
            SignInPanel.setVisible(false);
        }
    }
    
    private void showSignUpLoadingPanel() {
        isSigningUp = true;
        SigningUpPanel.setVisible(true);
        DividerLoadingPanel.setVisible(true);
        new Thread(() -> {
            String[] loadingStates = {"Signing up.", "Signing up..", "Signing up..."};
            AtomicInteger index = new AtomicInteger(0);
            while (isSigningUp) {
                try {
                    Thread.sleep(300);
                    SwingUtilities.invokeLater(() -> {
                        int currentIndex = index.getAndIncrement();
                        SigningUpLabel.setText(loadingStates[currentIndex % loadingStates.length]);
                    });
                } catch (InterruptedException e) {
                    Thread.currentThread().interrupt();
                    break;
                }
            }
            SwingUtilities.invokeLater(() -> SigningUpPanel.setVisible(false));
        }).start();
    }
    
    private void showSignInLoadingPanel() {
        isSigningIn = true;
        SigningInPanel.setVisible(true);
        DividerLoadingPanel.setVisible(true);
        new Thread(() -> {
            String[] loadingStates = {"Signing in.", "Signing in..", "Signing in..."};
            AtomicInteger index = new AtomicInteger(0);
            while (isSigningIn) {
                try {
                    Thread.sleep(300);
                    SwingUtilities.invokeLater(() -> {
                        int currentIndex = index.getAndIncrement();
                        SigningInLabel.setText(loadingStates[currentIndex % loadingStates.length]);
                    });
                } catch (InterruptedException e) {
                    Thread.currentThread().interrupt();
                    break;
                }
            }
            SwingUtilities.invokeLater(() -> SigningInPanel.setVisible(false));
        }).start();
    }
    
    private void hideLoadingPanel() {
        isSigningIn = false;
        isSigningUp = false;
        SigningInPanel.setVisible(false);
        SigningUpPanel.setVisible(false);
        DividerLoadingPanel.setVisible(false);
    }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        SigningUpPanel = new javax.swing.JPanel();
        SigningUpLabel = new javax.swing.JLabel();
        SigningInPanel = new javax.swing.JPanel();
        SigningInLabel = new javax.swing.JLabel();
        DividerLoadingPanel = new javax.swing.JPanel();
        SignInPanel = new javax.swing.JPanel();
        jlabel3 = new javax.swing.JLabel();
        SignUpLabelButton = new javax.swing.JLabel();
        signinButton = new javax.swing.JButton();
        signinPasswordField = new javax.swing.JPasswordField();
        passwordLabel1 = new javax.swing.JLabel();
        usernameLabel1 = new javax.swing.JLabel();
        signinUsernameField = new javax.swing.JTextField();
        showPasswordCheckBox1 = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        SignUpPanel = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        lastnameField = new javax.swing.JTextField();
        firstnameField = new javax.swing.JTextField();
        usernameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        signupUsernameField = new javax.swing.JTextField();
        signupPasswordField = new javax.swing.JPasswordField();
        showPasswordCheckBox = new javax.swing.JCheckBox();
        signupButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        SignInLabelButton = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        AdminPanel = new javax.swing.JPanel();
        WelcomeAdminLabel = new javax.swing.JLabel();
        AdminLogoutButton = new javax.swing.JButton();
        UserPanel = new javax.swing.JPanel();
        WelcomeUserLabel = new javax.swing.JLabel();
        UserLogoutButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simple Login System");

        MainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SigningUpPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        SigningUpLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        SigningUpLabel.setText("Signing up");

        javax.swing.GroupLayout SigningUpPanelLayout = new javax.swing.GroupLayout(SigningUpPanel);
        SigningUpPanel.setLayout(SigningUpPanelLayout);
        SigningUpPanelLayout.setHorizontalGroup(
            SigningUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SigningUpPanelLayout.createSequentialGroup()
                .addContainerGap(81, Short.MAX_VALUE)
                .addComponent(SigningUpLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        SigningUpPanelLayout.setVerticalGroup(
            SigningUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SigningUpPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(SigningUpLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        MainPanel.add(SigningUpPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, -1, -1));

        SigningInPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        SigningInLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        SigningInLabel.setText("Signing in");

        javax.swing.GroupLayout SigningInPanelLayout = new javax.swing.GroupLayout(SigningInPanel);
        SigningInPanel.setLayout(SigningInPanelLayout);
        SigningInPanelLayout.setHorizontalGroup(
            SigningInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SigningInPanelLayout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addComponent(SigningInLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        SigningInPanelLayout.setVerticalGroup(
            SigningInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SigningInPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(SigningInLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        MainPanel.add(SigningInPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, -1, -1));

        DividerLoadingPanel.setEnabled(false);
        DividerLoadingPanel.setOpaque(false);
        DividerLoadingPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DividerLoadingPanelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout DividerLoadingPanelLayout = new javax.swing.GroupLayout(DividerLoadingPanel);
        DividerLoadingPanel.setLayout(DividerLoadingPanelLayout);
        DividerLoadingPanelLayout.setHorizontalGroup(
            DividerLoadingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );
        DividerLoadingPanelLayout.setVerticalGroup(
            DividerLoadingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );

        MainPanel.add(DividerLoadingPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 380));

        SignInPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlabel3.setText("Don't have an account?");
        SignInPanel.add(jlabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 260, -1, -1));

        SignUpLabelButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        SignUpLabelButton.setText("Sign up");
        SignUpLabelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignUpLabelButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SignUpLabelButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SignUpLabelButtonMouseExited(evt);
            }
        });
        SignInPanel.add(SignUpLabelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 260, -1, -1));

        signinButton.setText("Sign in");
        signinButton.setNextFocusableComponent(SignUpLabelButton);
        signinButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signinButtonActionPerformed(evt);
            }
        });
        SignInPanel.add(signinButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 210, 30));

        signinPasswordField.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        signinPasswordField.setNextFocusableComponent(showPasswordCheckBox1);
        signinPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signinPasswordFieldActionPerformed(evt);
            }
        });
        SignInPanel.add(signinPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 210, 30));

        passwordLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        passwordLabel1.setText("Password");
        SignInPanel.add(passwordLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 60, 30));

        usernameLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        usernameLabel1.setText("Username");
        SignInPanel.add(usernameLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, 30));

        signinUsernameField.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        signinUsernameField.setForeground(new java.awt.Color(153, 153, 153));
        signinUsernameField.setText("Enter Username");
        signinUsernameField.setNextFocusableComponent(signinPasswordField);
        signinUsernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signinUsernameFieldActionPerformed(evt);
            }
        });
        SignInPanel.add(signinUsernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 210, 30));

        showPasswordCheckBox1.setText("Show Password?");
        showPasswordCheckBox1.setNextFocusableComponent(signinButton);
        showPasswordCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPasswordCheckBox1ActionPerformed(evt);
            }
        });
        SignInPanel.add(showPasswordCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 185, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel4.setText("Simple Login System");
        SignInPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

        MainPanel.add(SignInPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 380));

        SignUpPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nameLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        nameLabel.setText("Name");
        SignUpPanel.add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 40, 30));

        lastnameField.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        lastnameField.setForeground(new java.awt.Color(153, 153, 153));
        lastnameField.setText("Last Name");
        lastnameField.setNextFocusableComponent(signupUsernameField);
        lastnameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastnameFieldActionPerformed(evt);
            }
        });
        SignUpPanel.add(lastnameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 100, 30));

        firstnameField.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        firstnameField.setForeground(new java.awt.Color(153, 153, 153));
        firstnameField.setText("First Name");
        firstnameField.setNextFocusableComponent(lastnameField);
        firstnameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnameFieldActionPerformed(evt);
            }
        });
        SignUpPanel.add(firstnameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 100, 30));

        usernameLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        usernameLabel.setText("Username");
        SignUpPanel.add(usernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, 30));

        passwordLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        passwordLabel.setText("Password");
        SignUpPanel.add(passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 60, 30));

        signupUsernameField.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        signupUsernameField.setForeground(new java.awt.Color(153, 153, 153));
        signupUsernameField.setText("Enter Username");
        signupUsernameField.setNextFocusableComponent(signupPasswordField);
        signupUsernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupUsernameFieldActionPerformed(evt);
            }
        });
        SignUpPanel.add(signupUsernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 210, 30));

        signupPasswordField.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        signupPasswordField.setNextFocusableComponent(showPasswordCheckBox);
        signupPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupPasswordFieldActionPerformed(evt);
            }
        });
        SignUpPanel.add(signupPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 210, 30));

        showPasswordCheckBox.setText("Show Password?");
        showPasswordCheckBox.setNextFocusableComponent(signupButton);
        showPasswordCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPasswordCheckBoxActionPerformed(evt);
            }
        });
        SignUpPanel.add(showPasswordCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 185, -1, -1));

        signupButton.setText("Sign up");
        signupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupButtonActionPerformed(evt);
            }
        });
        SignUpPanel.add(signupButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 210, 30));

        jLabel1.setText("Already have an account?");
        SignUpPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 260, -1, -1));
        jLabel1.getAccessibleContext().setAccessibleName("");

        SignInLabelButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        SignInLabelButton.setText("Sign in");
        SignInLabelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignInLabelButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SignInLabelButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SignInLabelButtonMouseExited(evt);
            }
        });
        SignUpPanel.add(SignInLabelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 260, -1, -1));
        SignInLabelButton.getAccessibleContext().setAccessibleName("");

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel2.setText("Simple Login System");
        SignUpPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

        MainPanel.add(SignUpPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 380));

        AdminPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        WelcomeAdminLabel.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        WelcomeAdminLabel.setText("Hi Admin");
        AdminPanel.add(WelcomeAdminLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 67, -1, -1));

        AdminLogoutButton.setText("Log out");
        AdminLogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminLogoutButtonActionPerformed(evt);
            }
        });
        AdminPanel.add(AdminLogoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 90, 40));

        MainPanel.add(AdminPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 380));

        UserPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        WelcomeUserLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        WelcomeUserLabel.setText("Welcome");
        UserPanel.add(WelcomeUserLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 450, 80));

        UserLogoutButton.setText("Log out");
        UserLogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserLogoutButtonActionPerformed(evt);
            }
        });
        UserPanel.add(UserLogoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 90, 40));

        MainPanel.add(UserPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 380));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void firstnameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnameFieldActionPerformed

    private void lastnameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastnameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastnameFieldActionPerformed

    private void signupUsernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupUsernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signupUsernameFieldActionPerformed

    private void signupPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signupPasswordFieldActionPerformed

    private void signupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupButtonActionPerformed
        if(!isValidInput()){
            // add error
        }
        
        showSignUpLoadingPanel();
        
        new Thread(() -> {
            String firstName = firstnameField.getText();
            String lastName = lastnameField.getText();
            String username = signupUsernameField.getText();
            String password = String.valueOf(signupPasswordField.getPassword());
            boolean success = signupUser(firstName, lastName, username, password);
            SwingUtilities.invokeLater(() -> {
                hideLoadingPanel();
                
                if (!success){
                    JOptionPane.showMessageDialog(this,
                            "Username already exists",
                            "Error",
                            JOptionPane.ERROR_MESSAGE);
                    return;
                }
                currentUsername = username;
                seeUserPanel();
            });
        }).start();
    }//GEN-LAST:event_signupButtonActionPerformed

    private void SignInLabelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignInLabelButtonMouseClicked
        isSignIn(true);
    }//GEN-LAST:event_SignInLabelButtonMouseClicked

    private void showPasswordCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPasswordCheckBoxActionPerformed
        if(showPasswordCheckBox.isSelected()){
            signupPasswordField.setEchoChar((char)0);
        } else {
            signupPasswordField.setEchoChar('*');
        }
    }//GEN-LAST:event_showPasswordCheckBoxActionPerformed

    private void SignInLabelButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignInLabelButtonMouseEntered
        SignInLabelButton.setText("<html><u>Sign in</u></html>");
    }//GEN-LAST:event_SignInLabelButtonMouseEntered

    private void SignInLabelButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignInLabelButtonMouseExited
        SignInLabelButton.setText("Sign in");
    }//GEN-LAST:event_SignInLabelButtonMouseExited

    private void SignUpLabelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignUpLabelButtonMouseClicked
        isSignIn(false);
    }//GEN-LAST:event_SignUpLabelButtonMouseClicked

    private void SignUpLabelButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignUpLabelButtonMouseEntered
        SignUpLabelButton.setText("<html><u>Sign up</u></html>");
    }//GEN-LAST:event_SignUpLabelButtonMouseEntered

    private void SignUpLabelButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignUpLabelButtonMouseExited
        SignUpLabelButton.setText("Sign up");
    }//GEN-LAST:event_SignUpLabelButtonMouseExited

    private void signinButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signinButtonActionPerformed
        if (!isValidInput()){
            return;
        }
        
        showSignInLoadingPanel();
        
        new Thread(() -> {
            String username = signinUsernameField.getText();
            String password = String.valueOf(signinPasswordField.getPassword());

            UserLoginResult result = loginUser(username, password);
            
            SwingUtilities.invokeLater(() -> {
                hideLoadingPanel(); 

                if(!result.isSuccess()){
                    return;
                }
                if(result.getUserType().equals("Admin")){
                    seeAdminPanel();
                }
                if(result.getUserType().equals("User")){
                    currentUsername = username;
                    seeUserPanel();
                }
            });
        }).start();
        
        
    }//GEN-LAST:event_signinButtonActionPerformed

    private void signinPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signinPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signinPasswordFieldActionPerformed

    private void signinUsernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signinUsernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signinUsernameFieldActionPerformed

    private void showPasswordCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPasswordCheckBox1ActionPerformed
        if(showPasswordCheckBox1.isSelected()){
            signinPasswordField.setEchoChar((char)0);
        } else {
            signinPasswordField.setEchoChar('*');
        }
    }//GEN-LAST:event_showPasswordCheckBox1ActionPerformed

    private void DividerLoadingPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DividerLoadingPanelMouseClicked
        evt.consume();
    }//GEN-LAST:event_DividerLoadingPanelMouseClicked

    private void AdminLogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminLogoutButtonActionPerformed
        seeLoginPanel();
    }//GEN-LAST:event_AdminLogoutButtonActionPerformed

    private void UserLogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserLogoutButtonActionPerformed
        seeLoginPanel();
    }//GEN-LAST:event_UserLogoutButtonActionPerformed
    
    private void initFieldListeners(){
        JTextField[] textFields = {
            firstnameField,
            lastnameField,
            signupUsernameField,
            signinUsernameField
        };
        for(JTextField textField : textFields){
            textField.addFocusListener(new FocusListener() {
                @Override
                public void focusGained(FocusEvent e) {
                    if (textField.getText().equals("Enter Username") || 
                        textField.getText().equals("First Name") || 
                        textField.getText().equals("Last Name")){
                        textField.setForeground(new Color(0,0,0));
                        textField.setText("");
                    }
                }

                @Override
                public void focusLost(FocusEvent e) {
                    if (textField.getText().isEmpty()){
                        if(textField == firstnameField){
                            textField.setText("First Name");
                        }else if(textField == lastnameField){
                            textField.setText("Last Name");
                        }else if(textField == signupUsernameField){
                            textField.setText("Enter Username");
                        }
                        textField.setForeground(new Color(153,153,153));
                    }
                }

            });
        }
    }

    private boolean signupUser(String firstname, String lastname, String username, String unhashedPassword){
        String checkQuery = "SELECT 1 FROM users WHERE username = ?";
        String insertQuery = "INSERT INTO users (user_first_name, user_last_name, username, user_password, user_type) VALUES (?, ?, ?, ?, ?)";
        String DBurl = "jdbc:mysql://localhost:3306/testdb";
        String DBusername = "root";
        String DBpassword = "yauder";
        String hashedPassword = BCrypt.hashpw(unhashedPassword, BCrypt.gensalt(10));
        try (Connection connect = DriverManager.getConnection(DBurl, DBusername, DBpassword)){
            try(PreparedStatement checkStatement = connect.prepareStatement(checkQuery)){
                checkStatement.setString(1, username);
                ResultSet rs = checkStatement.executeQuery();
                if (rs.next()) {
                    // Username exists
                    return false; 
                }
            }
            try(PreparedStatement pstatement = connect.prepareStatement(insertQuery)) {
                pstatement.setString(1, firstname);
                pstatement.setString(2, lastname);
                pstatement.setString(3, username);
                pstatement.setString(4, hashedPassword);
                pstatement.setString(5, "User");
                pstatement.executeUpdate();
                return true;
            }
        } catch (SQLException e) {
            e.printStackTrace();
            return false;
        }
    }

    private UserLoginResult loginUser(String username, String password) {
        String query = "SELECT user_password, user_type FROM users WHERE username = ?";
        String DBurl = "jdbc:mysql://localhost:3306/testdb";
        String DBusername = "root";
        String DBpassword = "yauder";

        try (Connection connect = DriverManager.getConnection(DBurl, DBusername, DBpassword);
            PreparedStatement pstatement = connect.prepareStatement(query)) {
            pstatement.setString(1, username);
            ResultSet result = pstatement.executeQuery();
            if (result.next()) {
                String storedHashedPassword = result.getString("user_password");
                String userType = result.getString("user_type");
                boolean passwordMatch = BCrypt.checkpw(password , storedHashedPassword);
                if (passwordMatch) {
                    return new UserLoginResult(passwordMatch, userType);
                } else {
                    hideLoadingPanel();
                    JOptionPane.showMessageDialog(this,
                            "Incorrect Password",
                            "Error",
                            JOptionPane.ERROR_MESSAGE);
                    return new UserLoginResult(false, null);
                }
            } else {
                hideLoadingPanel();
                JOptionPane.showMessageDialog(this,
                        "User not found",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
                return new UserLoginResult(false, null);
            }
        } catch (SQLException e) {
            return new UserLoginResult(false, null);
        }
    }
    
    private boolean isValidInput(){
//        if(isSignIn){{
//            
//        } else {
//                
//        }
        return true;
    }
    
    private void seeLoginPanel(){
        AdminPanel.setVisible(false);
        UserPanel.setVisible(false);
        SignInPanel.setVisible(true);
    }
    
    private void seeAdminPanel(){
        SignUpPanel.setVisible(false);
        SignInPanel.setVisible(false);
        AdminPanel.setVisible(true);
    }
    
    private void seeUserPanel(){
        SignUpPanel.setVisible(false);
        SignInPanel.setVisible(false);
        UserPanel.setVisible(true);
        WelcomeUserLabel.setText("Welcome " + currentUsername);
        signinUsernameField.setText("Enter Username");
        signinUsernameField.setForeground(new Color(153, 153, 153));
        signinPasswordField.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoginSystem().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdminLogoutButton;
    private javax.swing.JPanel AdminPanel;
    private javax.swing.JPanel DividerLoadingPanel;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JLabel SignInLabelButton;
    private javax.swing.JPanel SignInPanel;
    private javax.swing.JLabel SignUpLabelButton;
    private javax.swing.JPanel SignUpPanel;
    private javax.swing.JLabel SigningInLabel;
    private javax.swing.JPanel SigningInPanel;
    private javax.swing.JLabel SigningUpLabel;
    private javax.swing.JPanel SigningUpPanel;
    private javax.swing.JButton UserLogoutButton;
    private javax.swing.JPanel UserPanel;
    private javax.swing.JLabel WelcomeAdminLabel;
    private javax.swing.JLabel WelcomeUserLabel;
    private javax.swing.JTextField firstnameField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jlabel3;
    private javax.swing.JTextField lastnameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel passwordLabel1;
    private javax.swing.JCheckBox showPasswordCheckBox;
    private javax.swing.JCheckBox showPasswordCheckBox1;
    private javax.swing.JButton signinButton;
    private javax.swing.JPasswordField signinPasswordField;
    private javax.swing.JTextField signinUsernameField;
    private javax.swing.JButton signupButton;
    private javax.swing.JPasswordField signupPasswordField;
    private javax.swing.JTextField signupUsernameField;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JLabel usernameLabel1;
    // End of variables declaration//GEN-END:variables
}
class UserLoginResult{
        private final boolean success;
        private final String userType;

        public UserLoginResult(boolean success, String userType){
            this.success = success;
            this.userType = userType;
        }
        
        public boolean isSuccess(){
            return success;
        }

        public String getUserType(){
            return userType;
        }
}
